### ISSUE TITLE
LeapController module is not loaded with the below error

### ISSUE THREAD

**Issue by xiaosnowqiang** [ReinoutEyckerman/Leap-Motion-Integration-With-Slicer#1]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/surgical/Slicer-5.0.3-linux-amd64/lib/Python/lib/python3.9/imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/surgical/Leap-Motion-Integration-With-Slicer/src/LeapController.py", line 28, in <module>
    import Leap
  File "/home/surgical/Leap-Motion-Integration-With-Slicer/lib/Leap.py", line 28, in <module>
    LeapPython = swig_import_helper()
  File "/home/surgical/Leap-Motion-Integration-With-Slicer/lib/Leap.py", line 24, in swig_import_helper
    _mod = imp.load_module('LeapPython', fp, pathname, description)
  File "/home/surgical/Slicer-5.0.3-linux-amd64/lib/Python/lib/python3.9/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/surgical/Slicer-5.0.3-linux-amd64/lib/Python/lib/python3.9/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libLeap.so: cannot open shared object file: No such file or directory

**Comment by Vesyrak** [comment]
Hey, just wanted to let you know that this repository is no longer maintained as I no longer have access to a device.
Feel free to fork and update the code as you see fit.
